version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    environment:
      - DATABASE_URL=postgresql://postgres:admin123@db:5432/eventflow_db
    depends_on:
      - db

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prismavent
      POSTGRES_PASSWORD: prisma123
      POSTGRES_DB: prismavent_db01
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: